In [54]:
from numpy import *
print ("Etiquetas de la variable X:")
tags_x = []
filas = int (input ("Cuantas variables de X hay: "))
for i in range (filas):
    tags_x.append( input("Nombre de la etiqueta de (X): ") )


print ("Etiquetas de la variable Y:")
tags_y = []
columnas = int (input ("Cuantas variables de Y hay: "))
for i in range (columnas):
    tags_y.append( input("Nombre de la etiqueta de (Y): ") )

print ("Llenado de datos: ")
columna_aux = []
mat1=[]
tabla = {}
tabla1={}
suma = 0
for columna in tags_y:
    print ("Llenado para la fila '{0}'".format(columna))
    for i in range (filas):
        dato = int ( input ("Dato: ") )
        columna_aux.append( dato )
        mat1.append(dato)
       
        suma += dato
    columna_aux.append(suma)
    tabla[columna]=columna_aux
    tabla1[columna]=mat1
    mat1=[]
    columna_aux = []
    suma = 0


import pandas as pd
tags_x.append("Total")
data_frame = pd.DataFrame(tabla,index=tags_x)
data_frame['Total']=data_frame.sum(axis=1)
print (data_frame)
matriz1 =(array(data_frame))


#print(tabla1)
df=pd.DataFrame(tabla1)
matriz2=(array(df))
#print(matriz2)
matriz=matriz2.T
#print(matriz)


Total=sum(matriz)
mfila=[]
for p in range(columnas):
    mfila.append(sum(matriz[p]))
    print (matriz[p])
#print(mfila)
sumf=0
for x in range(columnas):
    sumf=sumf+((mfila[x])/Total)*math.log((mfila[x])/Total)
#print(sumf)
HX=-sumf
print("H(X) = ",HX)

a=array(matriz)
b=a.T
#print(b)

mcol=[]
for z in range(filas):
    mcol.append(sum(b[z]))
    print (b[z])
#print(mcol)

sumc=0
for x in range(filas):
    sumc=sumc+((mcol[x])/Total)*math.log((mcol[x])/Total)
#print(sumc)

HY=-sumc
print("H(Y) = ",HY)

suma=0
for i in range(columnas):
    for j in range(filas):
        suma=suma + ((matriz[i][j])/Total)*math.log((matriz[i][j])/Total)
#print(suma)

HXY=-suma

print ("El coeficiente asimétrico es U(Y/X): ",(HX+HY-HXY)/HY)



Etiquetas de la variable X:
Cuantas variables de X hay: 3
Nombre de la etiqueta de (X): Bueno
Nombre de la etiqueta de (X): Regular
Nombre de la etiqueta de (X): Malo
Etiquetas de la variable Y:
Cuantas variables de Y hay: 4
Nombre de la etiqueta de (Y): Bajo
Nombre de la etiqueta de (Y): Medio
Nombre de la etiqueta de (Y): Alto
Nombre de la etiqueta de (Y): Muy alto
Llenado de datos: 
Llenado para la fila 'Bajo'
Dato: 75
Dato: 35
Dato: 40
Llenado para la fila 'Medio'
Dato: 60
Dato: 70
Dato: 50
Llenado para la fila 'Alto'
Dato: 20
Dato: 30
Dato: 40
Llenado para la fila 'Muy alto'
Dato: 15
Dato: 25
Dato: 40
         Bajo  Medio  Alto  Muy alto  Total
Bueno      75     60    20        15    170
Regular    35     70    30        25    160
Malo       40     50    40        40    170
Total     150    180    90        80    500
[75 35 40]
[60 70 50]
[20 30 40]
[15 25 40]
H(X) =  1.3308630416655705
[75 60 20 15]
[35 70 30 25]
[40 50 40 40]
H(Y) =  1.098209540353189
El coeficiente asimétrico e